import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
       
public class recentPayment extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form recentPayment
     */
    public recentPayment() {
        initComponents();
        showEmployeeFromTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeetable = new javax.swing.JTable();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAYROLL SYSTEM");

        jPanel1.setBackground(new java.awt.Color(13, 138, 173));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\Jalb.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, Short.MAX_VALUE)
        );

        employeetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "BALANCE", "POSITION", "GIVEPAY", "TOTAL BALANCE"
            }
        ));
        jScrollPane1.setViewportView(employeetable);

        OK.setBackground(new java.awt.Color(109, 234, 250));
        OK.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        OK.setText("OK");
        OK.setFocusable(false);
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
     this.dispose();
    }//GEN-LAST:event_OKActionPerformed

    MainClass main = new MainClass();
    
    public ArrayList<Payments> getPaymentsList(){
        ArrayList<Payments> paymentsList = new ArrayList<Payments>();
        Connection Conn = main.getConnection();
        String sql = "Select * from paymentcheck";
        Statement stmt;
        ResultSet rs;
        
        try{
            stmt = Conn.createStatement();
            rs= stmt.executeQuery(sql);
            Payments payments;
            
            while(rs.next())
            {
                payments = new Payments(Integer.parseInt(rs.getString("id")),rs.getString("employee_name"),Float.parseFloat(rs.getString("balance")),rs.getString("position"),Float.parseFloat(rs.getString("givepay")),Float.parseFloat(rs.getString("totalbalance")));
                paymentsList.add(payments);
                
            }
    }catch(SQLException e){
        Logger.getLogger(checkDelete.class.getName()).log(Level.SEVERE,null,e);
    }
        return paymentsList;
    }
    
    public void showEmployeeFromTable(){
        ArrayList<Payments> list = getPaymentsList();
        DefaultTableModel model = (DefaultTableModel)employeetable.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int x = 0 ; x<list.size();x++)
        {
            row[0]=list.get(x).getid();
            row[1]=list.get(x).getemployee_name();
            row[2]=list.get(x).getbalance();
            row[3]=list.get(x).getPosition();
            row[4]=list.get(x).getgivepay();
            row[5]=list.get(x).gettotalbalance();
            model.addRow(row);
        }
    }
    
    public void ShowItem(int index)
    {
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
            if("Nimbus".equals(info.getName())){
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
        }catch(ClassNotFoundException ex) {
            
            java.util.logging.Logger.getLogger(checkDelete.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        }catch(InstantiationException ex) {
            
            java.util.logging.Logger.getLogger(checkDelete.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        }catch(IllegalAccessException ex) {
            
            java.util.logging.Logger.getLogger(checkDelete.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        }catch(javax.swing.UnsupportedLookAndFeelException ex) {
            
            java.util.logging.Logger.getLogger(checkDelete.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        }

        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recentPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JTable employeetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent arg0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
